### PR TITLE
Changed from static sleep timer to a random one

### PR DESCRIPTION
**Pull request by piitchyy**

### CODE REVIEW

**Comment by piitchyy** [comment]
Not a coder by any means, so theres probably a better way to do it. Reason for this is that its not a constant number so if there is an Anti-Cheat/Bot system in place, this may reduce bans. Should maybe consider making a config file to keep a min and max value of the timer.

**Comment by jackbayliss** [comment]
@piitchyy  Thanks for the PR, I agree with you.

**Comment by jackbayliss** [comment]
@piitchyy  I'm actually working on a new branch, but either this or something like this will be in there. Thanks again.

**Comment by piitchyy** [comment]
I was bored so I made a config.ini and cleaned up the files a bit. Also made a lazy run batch script.

**Comment by jackbayliss** [comment]
@piitchyy appreciated, I will apply any of your suitable changes to the [new branch](https://github.com/jackbayliss/Python-MissionChiefBot/tree/update-v1) at some point this week. I also think I’ll make an .exe for Windows, making it easier and not requiring python.

**Pull request merged**
